# Generated by Django 2.1.2 on 2018-11-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='org',
            new_name='orgJob',
        ),
        migrations.RemoveField(
            model_name='organizationaldetails',
            name='personal_detail',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='orgPersonal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_detail', to='classroom.OrganizationalDetails'),
        ),
    ]
