# Generated by Django 2.1.2 on 2018-11-05 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20181104_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='organizationaldetails',
            options={'verbose_name_plural': 'OrganizationalDetails'},
        ),
        migrations.AlterModelOptions(
            name='personaldetails',
            options={'verbose_name_plural': 'PersonalDetails'},
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
