# Generated by Django 2.1.2 on 2018-10-30 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_job_recruiterdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_decription',
            new_name='job_description',
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='drive_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='offer',
            field=models.IntegerField(choices=[(1, 'Job'), (2, 'Internship'), (3, 'Job + Internship')], default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='package',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='selection_process',
            field=models.IntegerField(choices=[(1, 'Shortlisting from Resumes'), (2, 'Written Test - Aptitude'), (3, 'Group Discussion'), (4, 'Personal Interview (Technical + HR)'), (5, 'Written Test - Technical')], default=1),
        ),
    ]
