# Generated by Django 2.1.1 on 2018-10-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_job_recruiterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation_year', models.IntegerField()),
                ('graduation_institute', models.CharField(max_length=256)),
                ('graduation_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('X_year', models.IntegerField()),
                ('X_institute', models.CharField(max_length=256)),
                ('X_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('XII_year', models.IntegerField()),
                ('XII_institute', models.CharField(max_length=256)),
                ('XII_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('postgrad_year', models.IntegerField()),
                ('postgrad_institute', models.CharField(max_length=256)),
                ('postgrad_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_field', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='resume_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Resume'),
        ),
    ]
