# Generated by Django 2.0.1 on 2018-11-04 18:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_job_recruiterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('organization_email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('organization_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RecruiterDetails',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_decription',
            new_name='job_description',
        ),
        migrations.AddField(
            model_name='job',
            name='date_of_posting',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='drive_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='job',
            name='offer',
            field=models.IntegerField(choices=[(1, 'Job'), (2, 'Internship'), (3, 'Job + Internship')], default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='package',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='job',
            name='selection_process',
            field=models.IntegerField(choices=[(1, 'Shortlisting from Resumes'), (2, 'Written Test - Aptitude'), (3, 'Group Discussion'), (4, 'Personal Interview (Technical + HR)'), (5, 'Written Test - Technical')], default=1),
        ),
        migrations.AddField(
            model_name='organizationaldetails',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='classroom.Job'),
        ),
        migrations.AddField(
            model_name='organizationaldetails',
            name='personal_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.PersonalDetails'),
        ),
    ]
