# Generated by Django 2.0.1 on 2018-11-04 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20181105_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationaldetails',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='classroom.OrganizationalDetails'),
        ),
    ]
