# Generated by Django 2.1.2 on 2018-10-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20181030_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterdetails',
            name='organization_logo',
        ),
        migrations.AlterField(
            model_name='recruiterdetails',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
