# Generated by Django 2.1.2 on 2018-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20181030_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdetails',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
