# Generated by Django 2.0.1 on 2018-10-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20181029_2333'),
        ('classroom', '0006_auto_20181030_1326'),
    ]

    operations = [
    ]
