# Generated by Django 2.1.2 on 2018-11-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20181106_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='classroom.OrganizationalDetails'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_detail', to='classroom.OrganizationalDetails'),
        ),
    ]
