# Generated by Django 2.0.1 on 2018-11-05 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20181105_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakenJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Organizational_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_jobs', to='classroom.OrganizationalDetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_quiz', to='classroom.Student')),
            ],
        ),
    ]
