# Generated by Django 2.0.1 on 2018-11-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20181029_2333'),
        ('classroom', '0007_auto_20181031_1336'),
    ]

    operations = [
    ]
