# Generated by Django 2.0.1 on 2018-11-05 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_takenjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenjob',
            name='applied_job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='classroom.Job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='takenjob',
            name='Organizational_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organization_name_id', to='classroom.OrganizationalDetails'),
        ),
        migrations.AlterField(
            model_name='takenjob',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='classroom.Student'),
        ),
    ]
