# Generated by Django 2.1.2 on 2018-11-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20181108_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='user',
        ),
    ]
