# Generated by Django 2.0.1 on 2018-11-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20181105_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenjob',
            name='applied_job',
            field=models.ForeignKey(blank='TRUE', null='TRUE', on_delete=django.db.models.deletion.CASCADE, related_name='applied_job', to='classroom.Job'),
        ),
    ]
