# Generated by Django 2.0.1 on 2018-11-01 10:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_merge_20181101_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('organization_email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('organization_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='education',
            name='resume_field',
        ),
        migrations.DeleteModel(
            name='RecruiterDetails',
        ),
        migrations.AddField(
            model_name='job',
            name='date_of_posting',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AddField(
            model_name='organizationaldetails',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Job'),
        ),
        migrations.AddField(
            model_name='organizationaldetails',
            name='personal_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.PersonalDetails'),
        ),
    ]
