# Generated by Django 2.1.2 on 2018-11-01 09:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20181031_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='organizationaldetails',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Job'),
        ),
        migrations.AddField(
            model_name='organizationaldetails',
            name='personal_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.PersonalDetails'),
        ),
    ]
