# Generated by Django 2.0.1 on 2018-11-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20181105_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenjob',
            name='Organizational_name',
        ),
    ]
