# Generated by Django 2.1.2 on 2018-11-01 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_auto_20181031_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='organization_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizational_detail', to='classroom.OrganizationalDetails'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='organization_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_detail', to='classroom.OrganizationalDetails'),
        ),
    ]
