# Generated by Django 2.1.2 on 2018-11-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_job_date_of_posting'),
        ('classroom', '0007_merge_20181030_1424'),
    ]

    operations = [
    ]
