# Generated by Django 2.0.1 on 2018-11-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_remove_takenjob_organizational_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='student',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
