# Generated by Django 2.0.1 on 2018-11-04 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20181102_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationaldetails',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='classroom.Job'),
        ),
    ]
