# Generated by Django 2.1.2 on 2018-11-08 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_personaldetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='classroom.OrganizationalDetails'),
        ),
    ]
