# Generated by Django 2.1.2 on 2018-11-01 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_auto_20181031_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='organization_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.OrganizationalDetails'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='organization_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classroom.OrganizationalDetails'),
        ),
    ]
