# Generated by Django 2.1.2 on 2018-11-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_auto_20181031_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='organization_name',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='organization_name',
        ),
    ]
